import { type RepeatMode, type State as NativeState, type TrackMetadata } from './NativeExpoNativeTrackPlayer';
import { AudioEvents, Event, TrackPlayerEvents, type PlaybackPositionEvent, type PlaybackStateEvent, type QueueUpdatedEvent, type TrackChangedEvent } from './events';
import type { EventName } from './events';
import { useCurrentTrack, useCurrentTrackIndex, usePlaybackState, useProgress, useQueue } from './hooks';
import type { AddTrack, Track } from './types/Track';
import type { ResourceObject } from './types/ResourceObject';
import type { TrackMetadataBase } from './types/TrackMetadataBase';
import { PitchAlgorithms, TrackTypes } from './constants';
import type { PitchAlgorithm, RepeatModeType, StateType, TrackType } from './constants';
export { State, RepeatModes } from './constants';
export declare function addToQueue(track: AddTrack): Promise<void>;
export declare function addQueue(tracks: AddTrack[]): Promise<void>;
export declare function getQueue(): Promise<TrackMetadata[]>;
export declare function removeFromQueue(trackId: string): Promise<void>;
export declare function clearQueue(): Promise<void>;
export declare function play(index?: number | null): Promise<void>;
export declare function pause(): Promise<void>;
export declare function stop(): Promise<void>;
export declare function skipToNext(): Promise<void>;
export declare function skipToPrevious(): Promise<void>;
export declare function skipToIndex(index: number): Promise<void>;
export declare function seekTo(positionMs: number): Promise<void>;
export declare function reset(): Promise<void>;
export declare function setRepeatMode(mode: RepeatMode, startMs?: number | null, endMs?: number | null): Promise<void>;
export declare function getRepeatMode(): Promise<RepeatMode>;
export declare function getCurrentTrack(): Promise<Track | null>;
export declare function getCurrentTrackIndex(): Promise<number>;
export declare function getPosition(): Promise<number>;
export declare function getDuration(): Promise<number>;
export declare function getPlaybackState(): Promise<NativeState>;
export declare function setVolume(volume: number): Promise<void>;
export declare function getVolume(): Promise<number>;
export declare function setRate(rate: number): Promise<void>;
export declare function getRate(): Promise<number>;
declare const TrackPlayer: {
    addToQueue: typeof addToQueue;
    addQueue: typeof addQueue;
    getQueue: typeof getQueue;
    removeFromQueue: typeof removeFromQueue;
    clearQueue: typeof clearQueue;
    play: typeof play;
    pause: typeof pause;
    stop: typeof stop;
    skipToNext: typeof skipToNext;
    skipToPrevious: typeof skipToPrevious;
    skipToIndex: typeof skipToIndex;
    seekTo: typeof seekTo;
    reset: typeof reset;
    setRepeatMode: typeof setRepeatMode;
    getRepeatMode: typeof getRepeatMode;
    getCurrentTrack: typeof getCurrentTrack;
    getCurrentTrackIndex: typeof getCurrentTrackIndex;
    getPosition: typeof getPosition;
    getDuration: typeof getDuration;
    getPlaybackState: typeof getPlaybackState;
    setVolume: typeof setVolume;
    getVolume: typeof getVolume;
    setRate: typeof setRate;
    getRate: typeof getRate;
};
export default TrackPlayer;
export type { EventName, RepeatMode, NativeState as PlaybackState, Track, AddTrack, TrackMetadata, TrackMetadataBase, ResourceObject, TrackType, PitchAlgorithm, RepeatModeType, StateType, };
export { AudioEvents, Event, TrackPlayerEvents, PitchAlgorithms, TrackTypes, useCurrentTrack, useCurrentTrackIndex, usePlaybackState, useProgress, useQueue, };
export type { PlaybackPositionEvent, PlaybackStateEvent, QueueUpdatedEvent, TrackChangedEvent, };
//# sourceMappingURL=index.d.ts.map